<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Disability Customer Support_nav-cover</name>
   <tag></tag>
   <elementGuidId>a4597bc1-510c-4128-ab86-6d3060185cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-cover']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>194d0181-e476-4eab-a8e3-dcd9e60b68f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-cover</value>
      <webElementGuid>5d50a36f-65a2-4fbe-a93c-0901dd13d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-cover&quot;)</value>
      <webElementGuid>033f4b54-c8a8-4c88-af99-1473a31193d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-cover']</value>
      <webElementGuid>f8ff417e-00fa-46ed-8c54-7b682a0bb87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div[7]</value>
      <webElementGuid>f1e23ad9-4c33-49ab-9269-d78f9a7a3c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>a9305fb1-d62b-44aa-b132-fd2583662a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-cover']</value>
      <webElementGuid>2a2169ed-760e-44d6-ae6a-d5678ef82a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
